# Generated by Django 2.1.7 on 2019-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of product', max_length=200)),
                ('description', models.TextField(help_text='Description of product')),
                ('amount', models.IntegerField(help_text='Total product amount')),
            ],
        ),
    ]
