# Generated by Django 2.1.7 on 2019-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190214_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_title', models.CharField(help_text='Название категории', max_length=200)),
                ('catalog_icon', models.TextField(help_text='Класс иконки. Пример: fas fa-stream', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(help_text='Название подкатегории', max_length=200)),
            ],
        ),
    ]
