# Generated by Django 2.1.7 on 2019-02-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catalog_catalogitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='identity',
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='catalogitems',
            options={'verbose_name': 'ПодКатегории', 'verbose_name_plural': 'ПодКатегории'},
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='catalog_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='catalogitems',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Catalog'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_icon',
            field=models.CharField(help_text='Класс иконки. Пример: fas fa-stream', max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
