# Generated by Django 2.1.7 on 2019-02-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190217_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='title',
            new_name='catalog_title',
        ),
    ]
