# Generated by Django 2.1.7 on 2019-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190217_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title_needed', models.BooleanField(verbose_name='Нужна ли подпись к слайду?')),
                ('slider_title', models.CharField(help_text='Заголовок акции', max_length=200)),
                ('slider_img_path', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
