# Generated by Django 2.1.7 on 2019-02-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_slidera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitems',
            old_name='catalog',
            new_name='catalog_same',
        ),
    ]
