# Generated by Django 2.1.7 on 2019-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_img', models.ImageField(default='def', help_text='Фотографии магазинов', upload_to='main/img/foto/')),
            ],
            options={
                'verbose_name': 'Фотографии магазинов',
                'verbose_name_plural': 'Фотографии магазинов',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(default='def', help_text='Изображения новости', upload_to='main/img/news/'),
        ),
        migrations.AlterField(
            model_name='slidera',
            name='slider_img_path',
            field=models.ImageField(upload_to='main/img/slider/'),
        ),
    ]
