# Generated by Django 2.1.7 on 2019-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190222_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto_img',
        ),
        migrations.AddField(
            model_name='foto',
            name='foto_img1',
            field=models.ImageField(default='def', help_text='1-ая', upload_to='main/img/foto/'),
        ),
        migrations.AddField(
            model_name='foto',
            name='foto_img2',
            field=models.ImageField(default='def', help_text='2-ая', upload_to='main/img/foto/'),
        ),
        migrations.AddField(
            model_name='foto',
            name='foto_img3',
            field=models.ImageField(default='def', help_text='3-я', upload_to='main/img/foto/'),
        ),
        migrations.AddField(
            model_name='foto',
            name='foto_title',
            field=models.CharField(default='def', help_text='Альтернатива', max_length=200),
        ),
    ]
