# Generated by Django 2.1.7 on 2019-02-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190228_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('mymodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Catalog')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='related_fk',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='RelatedModel',
        ),
    ]
