# Generated by Django 2.1.7 on 2019-03-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190301_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinlinemodel',
            name='mymodel',
        ),
        migrations.DeleteModel(
            name='MyInlineModel',
        ),
    ]
