# Generated by Django 2.1.7 on 2019-03-01 13:29

from django.db import migrations
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190301_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidera',
            name='slider_img_path',
            field=django_thumbs.fields.ImageThumbsField(sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '800x600'},), upload_to='main/img/slider/'),
        ),
    ]
