# Generated by Django 2.1.7 on 2019-03-05 14:55

from django.db import migrations
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190301_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto_img1',
            field=django_thumbs.fields.ImageThumbsField(default='def', help_text='1-ая', sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '800x400'},), upload_to='main/img/foto/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto_img2',
            field=django_thumbs.fields.ImageThumbsField(default='def', help_text='2-ая', sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '800x400'},), upload_to='main/img/foto/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto_img3',
            field=django_thumbs.fields.ImageThumbsField(default='def', help_text='3-я', sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '800x400'},), upload_to='main/img/foto/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=django_thumbs.fields.ImageThumbsField(default='def', help_text='Изображения новости', sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '800x600'},), upload_to='main/img/news/'),
        ),
        migrations.AlterField(
            model_name='recomend',
            name='recomend_img',
            field=django_thumbs.fields.ImageThumbsField(default='def', help_text='картинка рекомендаций', sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '400x400'},), upload_to='main/img/recomend/'),
        ),
        migrations.AlterField(
            model_name='slidera',
            name='slider_img_path',
            field=django_thumbs.fields.ImageThumbsField(sizes=({'code': 'resized', 'resize': 'crop', 'wxh': '800x400'},), upload_to='main/img/slider/'),
        ),
    ]
