# Generated by Django 2.1.7 on 2019-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190305_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk_start_week', models.TimeField(blank=True)),
                ('wk_end_week', models.TimeField(blank=True)),
                ('sat_start_week', models.TimeField(blank=True)),
                ('sat_end_week', models.TimeField(blank=True)),
                ('sun_start_week', models.TimeField(blank=True)),
                ('sun_end_week', models.TimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Редактирование шапки',
                'verbose_name_plural': 'Редактирование шапки',
            },
        ),
    ]
