# Generated by Django 2.1.7 on 2019-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_headerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk_start_week', models.TimeField(blank=True, verbose_name='Время начала рабочего дня:')),
                ('wk_end_week', models.TimeField(blank=True, verbose_name='Время завершения рабочего дня:')),
                ('sat_start_week', models.TimeField(blank=True, verbose_name='Время начала рабочего дня:')),
                ('sat_end_week', models.TimeField(blank=True, verbose_name='Время завершения рабочего дня:')),
                ('sun_start_week', models.TimeField(blank=True, verbose_name='Время начала рабочего дня:')),
                ('sun_end_week', models.TimeField(blank=True, verbose_name='Время завершения рабочего дня:')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Время работы',
            },
        ),
        migrations.DeleteModel(
            name='HeaderInfo',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новостные акции', 'verbose_name_plural': 'Новостные акции'},
        ),
    ]
