# Generated by Django 2.1.7 on 2019-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190306_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_header', models.CharField(help_text='Общий заголовок', max_length=200, verbose_name='Общий заголовок:')),
                ('first_adress_header', models.CharField(help_text='Первый адрес', max_length=200, verbose_name='Первый адрес:')),
                ('first_number', models.CharField(help_text='Первый номер', max_length=200, verbose_name='Первый номер:')),
                ('first_email', models.EmailField(help_text='Первый email', max_length=200, verbose_name='Первый email:')),
                ('second_adress_header', models.CharField(help_text='Второй адрес', max_length=200, verbose_name='Второй адрес:')),
                ('second_number', models.CharField(help_text='Второй номер', max_length=200, verbose_name='Второй номер:')),
                ('second_email', models.EmailField(help_text='Второй email', max_length=200, verbose_name='Второй email:')),
            ],
            options={
                'verbose_name': 'Адреса магазинов',
                'verbose_name_plural': 'Адреса магазинов',
            },
        ),
    ]
