# Generated by Django 2.1.7 on 2019-03-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DitailMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Фотографии магазинов',
            },
        ),
        migrations.CreateModel(
            name='Hmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmenu_title', models.CharField(max_length=200)),
                ('hmenu_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['hmenu_order'],
            },
        ),
        migrations.CreateModel(
            name='HmenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(help_text='Название пункта меню', max_length=200)),
                ('hmenu_same', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hmenu')),
            ],
            options={
                'verbose_name': 'Пункты меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.AlterField(
            model_name='adress',
            name='common_header',
            field=models.CharField(max_length=200, verbose_name='Общий заголовок:'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='first_adress_header',
            field=models.CharField(max_length=200, verbose_name='Первый адрес:'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='first_email',
            field=models.EmailField(max_length=200, verbose_name='Первый email:'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='first_number',
            field=models.CharField(max_length=200, verbose_name='Первый номер:'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='second_adress_header',
            field=models.CharField(max_length=200, verbose_name='Второй адрес:'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='second_email',
            field=models.EmailField(max_length=200, verbose_name='Второй email:'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='second_number',
            field=models.CharField(max_length=200, verbose_name='Второй номер:'),
        ),
    ]
