# Generated by Django 2.1.7 on 2019-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190317_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='first_number',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='second_number',
        ),
        migrations.AddField(
            model_name='adress',
            name='first_number1',
            field=models.CharField(default='', max_length=200, verbose_name='Номер:'),
        ),
        migrations.AddField(
            model_name='adress',
            name='first_number2',
            field=models.CharField(default='', max_length=200, verbose_name='Номер:'),
        ),
        migrations.AddField(
            model_name='adress',
            name='first_number3',
            field=models.CharField(default='', max_length=200, verbose_name='Номер:'),
        ),
        migrations.AddField(
            model_name='adress',
            name='second_number1',
            field=models.CharField(default='', max_length=200, verbose_name='Номер:'),
        ),
        migrations.AddField(
            model_name='adress',
            name='second_number2',
            field=models.CharField(default='', max_length=200, verbose_name='Номер:'),
        ),
        migrations.AddField(
            model_name='adress',
            name='second_number3',
            field=models.CharField(default='', max_length=200, verbose_name='Номер:'),
        ),
    ]
