# Generated by Django 2.1.7 on 2019-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190317_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitems',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
