# Generated by Django 2.1.7 on 2019-03-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190325_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_items',
            options={'verbose_name': 'Товарные позиции', 'verbose_name_plural': 'Товарные позиции'},
        ),
        migrations.AddField(
            model_name='catalogitems',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
        migrations.AlterField(
            model_name='detail_items',
            name='detail_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CatalogItems', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='detail_items',
            name='detail_cost',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='detail_items',
            name='detail_description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='detail_items',
            name='detail_title',
            field=models.CharField(help_text='Наименование товара', max_length=200, verbose_name='Наименование'),
        ),
    ]
