# Generated by Django 2.1.7 on 2019-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190325_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
